create-mob-catalog
Sashko-kapillar/Team-GoIT-project-13 pull request #10
Opened 2024-06-28 21:43 UTC by VitaliiChef

2024-06-28 21:53 UTC, VitaliiChef commented
А ми продовжуємо продовжувати )))

2024-06-28 22:32 UTC, Sashko-kapillar requested changes
треба трошки допрацювати

2024-06-28 22:32 UTC, Sashko-kapillar commented on src/css/catalog.css
> +.catalog-item {
для лішки прибери маржин

2024-06-28 22:32 UTC, Sashko-kapillar commented on src/css/catalog.css
> +  margin-bottom: 60px;
маржин-ботом 15рх від кнопки

2024-06-28 22:32 UTC, Sashko-kapillar commented on src/css/catalog.css
> +.btn-show-more {
дороби кнопці ховер та фокус

2024-06-28 22:50 UTC, VitaliiChef commented on src/css/catalog.css
> +.btn-show-more {
![no-mb-15](https://github.com/Sashko-kapillar/Team-GoIT-project-13/assets/167873039/7464c6a2-0f96-4fb1-9164-2aa2eb7126cf)
коли прибрав маржин на лішку

2024-06-28 22:51 UTC, VitaliiChef commented on src/css/catalog.css
> +.btn-show-more {
вони прилипли один до одної

2024-06-28 23:06 UTC, VitaliiChef commented on src/css/catalog.css
> +.btn-show-more {
замінив на паддіннг, працює

2024-06-29 15:43 UTC, Sashko-kapillar approved these changes
добра робота

2024-06-29 15:46 UTC, merged