Adw desk
Sashko-kapillar/Team-GoIT-project-13 pull request #26
Opened 2024-06-30 11:38 UTC by Vitaly-Stefanyshyn777

Зробив таблетну і десктопну версію разом

2024-06-30 20:24 UTC, yuliia-shl commented on src/css/advertisement.css
> +      line-height: 0.92;
margin-bottom: 32px;

2024-06-30 20:25 UTC, yuliia-shl commented on src/css/advertisement.css
> +    z-index: 2;
displey: flex;

2024-06-30 20:28 UTC, yuliia-shl commented on src/css/advertisement.css
> +    background-image: url(/advertisement_x1-mob.png);
не вірний шлях

2024-06-30 20:29 UTC, yuliia-shl requested changes
виправ зауваження

2024-07-01 08:07 UTC, Sashko-kapillar approved these changes
гарна робота

2024-07-01 08:07 UTC, Sashko-kapillar commented on src/css/advertisement.css
> +    position: relative;
релатів та з-індекс тут не потрібні

2024-07-01 08:07 UTC, Sashko-kapillar commented on src/css/advertisement.css
фонова картинка не завантажується

2024-07-01 08:08 UTC, Sashko-kapillar approved these changes

2024-07-01 08:09 UTC, Sashko-kapillar approved these changes

2024-07-01 08:14 UTC, yuliia-shl approved these changes

2024-07-01 08:16 UTC, merged