aboutus-desktop
Sashko-kapillar/Team-GoIT-project-13 pull request #29
Opened 2024-06-30 14:11 UTC by Kharisova-Anna

-видалила старі зображення  
-додала нові зображення для mob-, tab-, desktop- версій

2024-06-30 19:12 UTC, Sashko-kapillar requested changes

2024-06-30 19:12 UTC, Sashko-kapillar commented on src/partials/aboutus.html
>  <section class="about-us">
<section class="about-us **section**">  додати клас section

2024-07-01 08:28 UTC, yuliia-shl approved these changes
все супер)

2024-07-01 08:29 UTC, yuliia-shl approved these changes

2024-07-01 11:40 UTC, Sashko-kapillar approved these changes

2024-07-01 11:40 UTC, merged