Section: Sale (mob)
Sashko-kapillar/Team-GoIT-project-13 pull request #4
Opened 2024-06-27 14:36 UTC by yuliia-shl

-додана секція sale на мобільну версію.
-замінені картинки для моб версії на png замість webp
-додані глобальні стилі body, container, title на всі брейкпоінти
-видалений зайвий слеш в index.html - load about us
-доданий нормалайз

2024-06-27 15:16 UTC, Sashko-kapillar commented on src/css/reset.css
> +body {
цю зміну можеш відкотити щоб не було конфлікту

2024-06-27 15:31 UTC, Sashko-kapillar requested changes

2024-06-27 15:31 UTC, Sashko-kapillar commented on src/css/reset.css
> +body {
краще відкотити цю зміну

2024-06-27 15:31 UTC, Sashko-kapillar commented on src/css/reset.css
> +.container {
це прописано разом з padding: 0 20px;

2024-06-27 15:31 UTC, Sashko-kapillar commented on src/css/reset.css
> +  .title {
повторюється селектор для чого?

2024-06-27 19:30 UTC, yuliia-shl commented on src/css/reset.css
> +body {
відкотила

2024-06-27 19:30 UTC, yuliia-shl commented on src/css/reset.css
> +  .title {
вже змерджила, виправлено

2024-06-28 07:24 UTC, Sashko-kapillar approved these changes
ок!

2024-06-28 07:24 UTC, merged