22:39 add resize for textarea + pattern
Sashko-kapillar/Team-GoIT-project-13 pull request #44
Opened 2024-07-01 19:46 UTC by Zavhorodnij

Патерн стояв , не знаю , що не так , всееяк в завданні . Resize-none додав до текст ареа

2024-07-01 21:45 UTC, yuliia-shl commented on src/partials/contactus.html
> +                            <input type="tel" class="modal-input" name="user-phone" id="user-phone" placeholder="+380"
додай 
title="(+380-XX-XXX-XX-XX)" required

2024-07-01 21:46 UTC, Sashko-kapillar reviewed
до селектору .modal-textarea {         resize: none; } щоб поле на ламалося

2024-07-01 21:47 UTC, yuliia-shl commented on src/partials/contactus.html
> +                                placeholder="Email" pattern="([A-z0-9_.-]{1,})@([A-z0-9_.-]{1,}).([A-z]{2,8})" />
зг. ТЗ додай у всіх input:
required

2024-07-01 21:51 UTC, yuliia-shl requested changes
38 рядок - зайвий тег "<label>"

2024-07-02 02:18 UTC, Sashko-kapillar approved these changes

2024-07-02 17:43 UTC, Sashko-kapillar approved these changes
далі буде

2024-07-03 06:29 UTC, yuliia-shl approved these changes

2024-07-03 06:30 UTC, merged